component: website
name: shortenUrl-frontend

inputs:
  src:
    src: ./
    hook: npm i && npm run build
    dist: ./build
    index: index.html
    error: index.html
  region: ap-guangzhou
  bucketName: shorten-url-frontend
  protocol: https
  env:
    apiUrl: ${output:${stage}:${app}:shortenUrl-backend.apigw.url}
