component: http
name: shortenUrl-backend
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    runtime: Nodejs14.18
    timeout: 100
    framework: koa
    name: ${name}
    installDependency: true
    vpc:
      vpcId: ${env:vpcId}
      subnetId: ${env:subnetId}
    environments:
      - key: dbConnUrl
        value: ${output:${stage}:${app}:shortenUrl-db.private.connectionString}
      - key: authPass
        value: ${env:authPass}
  apigw:
    api:
      cors: true
    protocols:
      - http
      - https
    environment: release
